name = "MaNN"
uuid = "01d9f056-b8c9-4140-9107-6f1a0def3c7a"
authors = ["Johannes Nägele"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
